config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings
from task.views import UserLoginView, HomePageRedirectView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageRedirectView.as_view(), name='first_page'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('task/', include('task.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/urls.py
from django.urls import path

from task.views import TodoListView, TodoCreateView, TodoDeleteView, TodoUpdateView, TodoExportView, TodoImportView, \
    UserStatisticsView, UserProfileView

app_name = 'task'

urlpatterns = [
    path('todo_list/', TodoListView.as_view(), name='todo_list'),
    path('todo_create/', TodoCreateView.as_view(), name='todo_create'),
    path('todo_delete/<int:id>/', TodoDeleteView.as_view(), name='todo_delete'),

    path('todo_update/complete/<int:id>/', TodoUpdateView.as_view(), name='todo_update_complete'),
    path('todo_update/uncomplete/<int:id>/', TodoUpdateView.as_view(), name='todo_update_uncomplete'),

    path('todo_export/', TodoExportView.as_view(), name='todo_export'),
    path('todo_import/', TodoImportView.as_view(), name='todo_import'),

    path('user_statistics/', UserStatisticsView.as_view(), name='user_statistics'),
    path('user_profile/', UserProfileView.as_view(), name='user_profile'),
]

task/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext as _


class Todo(models.Model):
    user = models.ForeignKey(User, models.CASCADE)
    text = models.TextField(_('To do text'))
    is_completed = models.BooleanField(_('Task status'), default=False)
    created_time = models.DateTimeField(_('Time when task created'), auto_now_add=True)
    last_updated = models.DateTimeField(_('Last time when task updated'), auto_now=True)

    class Meta:
        ordering = ('-id',)

    @property
    def get_user_full_name(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)

task/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import ugettext_lazy as _

from task.models import Todo


class LoginForm(forms.Form):
    email = forms.CharField(
        label=_('Email'),
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Email'),
        })
    )
    password = forms.CharField(
        label=_('Password'),
        max_length=100,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': _('Password'),
        })
    )


class SignUpForm(forms.Form):
    first_name = forms.CharField(
        label=_('First Name'),
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'form-control signupName',
            'placeholder': _('First Name'),
        })
    )
    last_name = forms.CharField(
        label=_('Last Name'),
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'form-control signupLastName',
            'placeholder': _('Last Name'),
        })
    )
    email_address = forms.CharField(
        label=_('Email Address'),
        max_length=100,
        widget=forms.EmailInput(attrs={
            'class': 'form-control signupEmail',
            'placeholder': _('Email Address'),
        })
    )
    password = forms.CharField(
        label=_('Password'),
        max_length=100,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control signupPassword',
            'placeholder': _('Password'),
        })
    )
    confirm_password = forms.CharField(
        label=_('Confirm Password'),
        max_length=100,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control signupPasswordConfirm',
            'placeholder': _('Confirm Password'),
        })
    )


class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo
        fields = ['text']
        labels = {
            'text': _('Todo')
        }
        widgets = {
            'text': forms.TextInput(attrs={'class': 'form-control'})
        }

task/views.py
import csv
import io
from itertools import islice

from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db import transaction
from django.db.models import Count, Q
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, RedirectView, FormView, CreateView, DeleteView, UpdateView, TemplateView
from django.views import View
from django.utils.translation import gettext as _

from config._ajax import AjaxResponseMixin
from task.forms import TodoForm, LoginForm
from task.models import Todo

__all__ = ('LogoutView', 'UserLoginView', 'HomePageRedirectView', 'TodoListView', 'TodoCreateView', 'TodoDeleteView',
           'TodoUpdateView', 'TodoExportView', 'TodoImportView', 'UserStatisticsView')


class LogoutView(LoginRequiredMixin, RedirectView):
    url = reverse_lazy('login')

    def get(self, request, **kwargs):
        logout(request)

        if request.GET.get('next'):
            self.url = '{}?next={}'.format(self.url, request.GET.get('next'))

        return super(LogoutView, self).get(request, **kwargs)


class UserLoginView(FormView):
    template_name = 'login.html'
    form_class = LoginForm

    def get(self, request, **kwargs):
        if self.request.user.is_authenticated:
            return redirect(reverse('task:todo_list'))

        return super(UserLoginView, self).get(request, **kwargs)

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')

        profile = User.objects.filter(email=email)

        if not profile:
            messages.error(self.request, _('User not found'))
            return self.form_invalid(form)

        profile = profile[0]
        if not profile.is_active:
            messages.error(self.request, _('User status is not active'))
            return self.form_invalid(form)

        user = authenticate(username=profile.username, password=password)

        if not user:
            messages.error(self.request, _('Wrong password'))
            return self.form_invalid(form)

        login(self.request, user)

        if self.request.GET.get('next'):
            url = self.request.GET.get('next')
        else:
            url = reverse('task:todo_list')

        return redirect(url)


class HomePageRedirectView(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return reverse('task:todo_list')
        return reverse('login')


class UserProfileView(TemplateView):
    template_name = 'user_profile.html'


class TodoListView(LoginRequiredMixin, ListView):
    model = Todo
    paginate_by = 4
    form_class = TodoForm
    
    def get_context_data(self, *args, **kwargs):
        context = super(TodoListView, self).get_context_data(**kwargs)
        context['form'] = self.form_class
        return context


class TodoCreateView(LoginRequiredMixin, CreateView):
    model = Todo
    fields = ['text']

    @transaction.atomic
    def form_valid(self, form):
        task = form.save(commit=False)
        task.user_id = self.request.user.id
        task.save()
        messages.success(self.request, _('Todo was created'))
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse('task:todo_list')


class TodoDeleteView(LoginRequiredMixin, DeleteView):
    model = Todo

    def get_object(self, queryset=None):
        _id = self.kwargs.get('id')
        return get_object_or_404(self.model, id=_id, user_id=self.request.user.id)

    def get_success_url(self):
        return reverse('task:todo_list')

    @transaction.atomic
    def get(self, request, *args, **kwargs):
        object = self.get_object()
        success_url = self.get_success_url()
        object.delete()
        messages.success(self.request, _('Todo was deleted'))
        return redirect(success_url)


class TodoUpdateView(LoginRequiredMixin, AjaxResponseMixin, UpdateView):
    model = Todo

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, id=self.kwargs.get('id'), user_id=self.request.user.id)

    def get_ajax(self, request, *args, **kwargs):
        object = self.get_object()
        if reverse('task:todo_update_complete', kwargs={'id': kwargs.get('id')}) == request.path:
            object.is_completed = True
        elif reverse('task:todo_update_uncomplete', kwargs={'id': kwargs.get('id')}) == request.path:
            object.is_completed = False
        object.save(update_fields=['is_completed', 'last_updated'])
        return render(request, 'task/todo_list_single_row.html', {'object': object})


class TodoExportView(LoginRequiredMixin, View):
    queryset = Todo.objects.all()

    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="todo_list.csv"'

        writer = csv.writer(response)
        writer.writerow(['User', 'Todo', 'Status', 'Created', 'Updated'])
        for obj in self.queryset.iterator():
            status = 'Completed' if obj.is_completed else 'Not Completed'
            writer.writerow([obj.get_user_full_name, obj.text, status,
                             obj.created_time.astimezone().strftime("%d-%m-%Y %H:%M:%S"),
                             obj.last_updated.astimezone().strftime("%d-%m-%Y %H:%M:%S")])

        return response


class TodoImportView(LoginRequiredMixin, View):
    model = Todo
    success_url = reverse_lazy('task:todo_list')

    def bulk_create(self, objs):
        while True:
            batch = list(islice(objs, 100))
            if not batch:
                break
            self.model.objects.bulk_create(batch)

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        csv_file = request.FILES.get('csv_file')
        if not csv_file.content_type == 'text/csv':
            messages.error(request, _('Format error!'))
            return redirect(self.success_url)
        dataset = csv_file.read().decode('UTF-8')
        io_string = io.StringIO(dataset)
        next(io_string)

        objs = []
        for row in csv.reader(io_string, delimiter=','):
            status = True if row[1] == 'Completed' else False
            objs.append(self.model(user_id=request.user.id, text=row[0], is_completed=status))
        self.bulk_create(iter(objs))
        messages.success(request, _('Todo was created'))

        return redirect(self.success_url)


class UserStatisticsView(LoginRequiredMixin, TemplateView):
    template_name = 'task/user_statistics.html'

    def get_context_data(self, **kwargs):
        context = super(UserStatisticsView, self).get_context_data(**kwargs)
        counts = Todo.objects.filter(user_id=self.request.user.id).aggregate(
            completed_count=Count('id', filter=Q(is_completed=True)),
            not_completed_count=Count('id', filter=Q(is_completed=False))
        )
        context['objs_count_list'] = counts
        completed_percentage = int((100 * counts['completed_count']) / (counts['completed_count'] + counts['not_completed_count']))
        context['percentages_list'] = [completed_percentage, 100 - completed_percentage]
        return context

templates/task/todo_list.html
{% extends 'base.html' %}

{% block title %}
    <title>Todo App - Home</title>
{% endblock title %}

{% block nav_items %}
    <li class="nav-item">
        <a class="nav-link font-weight-light active" href="{% url 'task:todo_list' %}">Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link font-weight-light" href="{% url 'task:user_statistics' %}">Statistics</a>
    </li>
{% endblock nav_items %}

{% block content %}

    <section id="about">
        <div class="container">
            <div class="row">
                <h2 class="col-md-12">Todo App</h2>
                <p class="col-md-12">A simple todo app</p>
                <div class="col-md-12 mb-2">
                    <button type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#exampleModal">Create</button>
                    <button type="button" class="btn btn-outline-warning import_csv_btn">Import</button>
                    <form enctype="multipart/form-data" style="display: none" id="todo_import_form" method="post" action="{% url 'task:todo_import' %}">
                        {% csrf_token %}
                        <input type="file" name="csv_file" id="csv_file_input_id">
                    </form>
                    <button type="button" class="btn btn-outline-dark float-right"><a href="{% url 'task:todo_export' %}">Export</a></button>
                </div>
                <div class="col-lg-12 mx-auto">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">User</th>
                            <th scope="col">Todo</th>
                            <th scope="col">Status</th>
                            <th scope="col">Created</th>
                            <th scope="col">Updated</th>
                            <th scope="col">Operations</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for todo in object_list %}
                        <tr>
                            <th scope="row">{{ todo.user.first_name }} {{ todo.user.last_name }}</th>
                            <td>{{ todo.text }}</td>
                            <td class="todo_status">{% if todo.is_completed %}
                                <button class="btn btn-success btn-sm">Completed</button>
                                {% else %}
                                <button class="btn btn-light btn-sm">Not Completed</button>
                                {% endif %}
                            </td>
                            <td>{{ todo.created_time }}</td>
                            <td>{{ todo.last_updated }}</td>
                            <td>
                            {% if request.user.id == todo.user_id %}
                                {% if todo.is_completed %}
                                <button type="button" class="btn btn-dark btn-sm todo_uncomplete" data-href="{% url 'task:todo_update_uncomplete' id=todo.id %}">Uncomplete</button>
                                {% else %}
                                <button type="button" class="btn btn-info btn-sm todo_complete" data-href="{% url 'task:todo_update_complete' id=todo.id %}">Complete</button>
                                {% endif %}

                                <button type="button" class="btn btn-danger btn-sm"><a href="{% url 'task:todo_delete' id=todo.id %}">Delete</a></button>
                            {% else %}
                                {% if todo.is_completed %}
                                <button type="button" class="btn btn-dark btn-sm not_allowed">Uncomplete</button>
                                {% else %}
                                <button type="button" class="btn btn-info btn-sm not_allowed">Complete</button>
                                {% endif %}

                                <button type="button" class="btn btn-danger btn-sm not_allowed">Delete</button>
                            {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                    {% endif %}
                    <li class="page-item"><a class="page-link">{{ page_obj.number }}</a></li>
                    {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>

        </div>
    </section>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Create Todo</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" action="{% url 'task:todo_create' %}" id="task_create_form">
                        <div class="form-group">
                            {% csrf_token %}
                            {{ form }}
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="task_create_btn">Save</button>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block script %}

<script>

    $('#task_create_btn').click(function () {
        $('#task_create_form').submit();
    });

    $(document).on('click', '.todo_complete', function () {
        var elem = $(this);
        var url = elem.attr('data-href');
        todo_update(url, 'complete', elem)
    });

    $(document).on('click', '.todo_uncomplete', function () {
        var elem = $(this);
        var url = elem.attr('data-href');
        todo_update(url, 'uncomplete', elem)
    });

    function todo_update(url, status, elem) {
        $.ajax({
            url:url,
            method:'get',
            success:function (data) {
                var tr = elem.parent().parent();
                //Added updated row
                $(data).insertAfter(tr);
                // Delete row
                tr.remove();

                var notfi = noty({text: 'Todo Updated', layout: 'topRight', type: 'success'});
                notfi.setTimeout(5000);
            },
            error:function (data) {
                var notfi = noty({text: 'Error', layout: 'topRight', type: 'error'});
                notfi.setTimeout(5000);
            }
        })
    }

    $(document).on('click', '.not_allowed', function () {
        var notfi = noty({text: 'Not Allowed', layout: 'topRight', type: 'error'});
        notfi.setTimeout(5000);
    });
    
    $('#csv_file_input_id').change(function () {
        $('#todo_import_form').submit()
    });
    
    $('.import_csv_btn').click(function () {
        $('#csv_file_input_id').trigger('click')
    })
</script>

{% endblock script %}

templates/task/todo_list_single_row.html
<tr>
    <th scope="row">{{ object.user.first_name }} {{ object.user.last_name }}</th>
    <td>{{ object.text }}</td>
    <td class="todo_status">{% if object.is_completed %}
        <button class="btn btn-success btn-sm">Completed</button>
    {% else %}
        <button class="btn btn-light btn-sm">Not Completed</button>
    {% endif %}
    </td>
    <td>{{ object.created_time }}</td>
    <td>{{ object.last_updated }}</td>
    <td>
        {% if object.is_completed and request.user.id == object.user_id %}
            <button type="button" class="btn btn-dark btn-sm todo_uncomplete" data-href="{% url 'task:todo_update_uncomplete' id=object.id %}">Uncomplete</button>
        {% elif request.user.id == object.user_id %}
            <button type="button" class="btn btn-info btn-sm todo_complete" data-href="{% url 'task:todo_update_complete' id=object.id %}">Complete</button>
        {% endif %}

        <button type="button" class="btn btn-danger btn-sm"><a href="{% url 'task:todo_delete' id=object.id %}">Delete</a></button>
    </td>
</tr>

templates/task/user_statistics.html
{% extends 'base.html' %}

{% block title %}
    <title>Todo App - Statistics</title>
{% endblock title %}

{% block nav_items %}
    <li class="nav-item">
        <a class="nav-link font-weight-light" href="{% url 'task:todo_list' %}">Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link font-weight-light active">Statistics</a>
    </li>
{% endblock nav_items %}

{% block content %}
    <section id="about col-md-2">
        <canvas id="myChart" width="400" height="400"></canvas>
    </section>
{% endblock content %}

{% block script %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" rel="stylesheet">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>

<script>
    data = {
        datasets: [{
            data: [{{ percentages_list.0 }}, {{ percentages_list.1 }}],
            backgroundColor: ['rgb(0,155,255)', 'rgb(0,255,114)']
        }],
        // These labels appear in the legend and in the tooltips when hovering different arcs
        labels: [
            'Completed ({{ objs_count_list.completed_count }})',
            'Not Completed ({{ objs_count_list.not_completed_count }})'
        ]
    };


    var options = {
        responsive: true,
        maintainAspectRatio: false,
    };

    var ctx = document.getElementById('myChart').getContext('2d');
    ctx.width = 500;
    ctx.height = 500;
    var myDoughnutChart = new Chart(ctx, {
        type: 'pie',
        data: data,
        options: options
    });
</script>
{% endblock script %}