config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings
from task.views import UserLoginView, HomePageRedirectView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageRedirectView.as_view(), name='first_page'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('task/', include('task.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/urls.py
from django.urls import path

from task.views import TodoListView, TodoCreateView, TodoDeleteView, TodoUpdateView, TodoExportView, TodoImportView, \
    UserStatisticsView, UserProfileView

app_name = 'task'

urlpatterns = [
    path('todo_list/', TodoListView.as_view(), name='todo_list'),
    path('todo_create/', TodoCreateView.as_view(), name='todo_create'),
    path('todo_delete/<int:id>/', TodoDeleteView.as_view(), name='todo_delete'),

    path('todo_update/complete/<int:id>/', TodoUpdateView.as_view(), name='todo_update_complete'),
    path('todo_update/uncomplete/<int:id>/', TodoUpdateView.as_view(), name='todo_update_uncomplete'),

    path('todo_export/', TodoExportView.as_view(), name='todo_export'),
    path('todo_import/', TodoImportView.as_view(), name='todo_import'),

    path('user_statistics/', UserStatisticsView.as_view(), name='user_statistics'),
    path('user_profile/', UserProfileView.as_view(), name='user_profile'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% block title %}{% endblock title %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

<body id="page-top">

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-blue fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Todo App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav">
                {% block nav_items %}{% endblock nav_items %}
            </ul>
        </div>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            User
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
            <button class="dropdown-item" type="button"><a href="{% url 'task:user_profile' %}">Profile</a></button>
            <button class="dropdown-item" type="button"><a href="{% url 'logout' %}">Logout</a></button>
          </div>
        </div>

    </div>
</nav>

{% block content %}{% endblock content %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'js/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<script type="text/javascript" src="{% static 'js/noty/jquery.noty.js' %}"></script>
<script type="text/javascript" src="{% static 'js/noty/layouts/topRight.js' %}"></script>
<script type="text/javascript" src="{% static 'js/noty/themes/default.js' %}"></script>

<script>
{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            var n = noty({text: '{{ message }}', layout: 'topRight', type: 'success'});
            n.setTimeout(5000);
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            var n = noty({text: '{{ message }}', layout: 'topRight', type: 'error'});
            n.setTimeout(5000);
        {% endif %}
    {% endfor %}
{% endif %}
</script>

{% block script %}{% endblock script %}

</body>

</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Sign In</h5>
                    <form class="form-signin" method="post">
                        {% csrf_token %}
                        <div class="form-label-group mb-3">
                            <label for="inputEmail">Email address</label>
                            {{ form.email }}
                        </div>

                        <div class="form-label-group mb-3">
                            <label for="inputPassword">Password</label>
                            {{ form.password }}
                        </div>

                        <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Sign in</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/jquery/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/noty/jquery.noty.js' %}"></script>
<script type="text/javascript" src="{% static 'js/noty/layouts/topRight.js' %}"></script>
<script type="text/javascript" src="{% static 'js/noty/themes/default.js' %}"></script>

<script>
{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            var n = noty({text: '{{ message }}', layout: 'topRight', type: 'success'});
            n.setTimeout(5000);
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            var n = noty({text: '{{ message }}', layout: 'topRight', type: 'error'});
            n.setTimeout(5000);
        {% endif %}
    {% endfor %}
{% endif %}
</script>

</body>
</html>

templates/user_profile.html
{% extends 'base.html' %}

{% block title %}
    <title>Todo App - Home</title>
{% endblock title %}

{% block nav_items %}
    <li class="nav-item">
        <a class="nav-link font-weight-light" href="{% url 'task:todo_list' %}">Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link font-weight-light" href="{% url 'task:user_statistics' %}">Statistics</a>
    </li>
{% endblock nav_items %}

{% block content %}

    <section id="about">
        <div class="container">
            <div class="row">
                <h2 class="col-md-12">User Information</h2>
                <p class="col-md-12">Full Name: {{ request.user.first_name }} {{ request.user.last_name }}</p>
                <p class="col-md-12">Email: {{ request.user.email }}</p>
            </div>
        </div>
    </section>

{% endblock content %}

{% block script %}

<script>

    $('#task_create_btn').click(function () {
        $('#task_create_form').submit();
    });

    $(document).on('click', '.todo_complete', function () {
        var elem = $(this);
        var url = elem.attr('data-href');
        todo_update(url, 'complete', elem)
    });

    $(document).on('click', '.todo_uncomplete', function () {
        var elem = $(this);
        var url = elem.attr('data-href');
        todo_update(url, 'uncomplete', elem)
    });

    function todo_update(url, status, elem) {
        $.ajax({
            url:url,
            method:'get',
            success:function (data) {
                var tr = elem.parent().parent();
                //Added updated row
                $(data).insertAfter(tr);
                // Delete row
                tr.remove();

                var notfi = noty({text: 'Todo Updated', layout: 'topRight', type: 'success'});
                notfi.setTimeout(5000);
            },
            error:function (data) {
                var notfi = noty({text: 'Error', layout: 'topRight', type: 'error'});
                notfi.setTimeout(5000);
            }
        })
    }

    $(document).on('click', '.not_allowed', function () {
        var notfi = noty({text: 'Not Allowed', layout: 'topRight', type: 'error'});
        notfi.setTimeout(5000);
    });
    
    $('#csv_file_input_id').change(function () {
        $('#todo_import_form').submit()
    });
    
    $('.import_csv_btn').click(function () {
        $('#csv_file_input_id').trigger('click')
    })
</script>

{% endblock script %}